spring.application.name=project

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=DSS;encrypt=false
spring.datasource.username=sa
spring.datasource.password=sriGanesh
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

aes.secret.key=Q7vX2kL9mP4nR8wE1jY5tA0bH6cF3dZ1

server.port=8080