package com.DSS.project.Service;

import com.DSS.project.Entity.AuditLog;
import com.DSS.project.Repository.AuditLogRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
@RequiredArgsConstructor
// To iterate through errors generated by a query
public class AuditLogService {

    private final AuditLogRepository auditLogRepository;

    // This is called when a query fails either validation or execution
    public void logFailure(String queryText, String dbType, String errorMessage) {
        AuditLog log = new AuditLog();
        log.setQueryText(queryText);
        log.setDbType(dbType);
        log.setErrorMessage(errorMessage);
        // timestamp is set automatically via @PrePersist
        auditLogRepository.save(log);
    }

    // To fetch all logs
    public List<AuditLog> getAllLogs() {
        return auditLogRepository.findAllByOrderByTimestampDesc();
    }

    // To fetch logs filtered by the type of database
    public List<AuditLog> getLogsByDbType(String dbType) {
        return auditLogRepository.findByDbType(dbType);
    }
}
